### ISSUE TITLE
Can I render "Selected Color" in GridShader.shader at multiple coordinate positions (id) at the same time?

### ISSUE THREAD

**Issue by LongwaterBoy** [r3eckon/Unity-SimpleGrid-Shader#2]
Can I render "Selected Color" in GridShader.shader at multiple coordinate positions (id) at the same time ?

**Comment by r3eckon** [comment]
Yes. You need to duplicate this block of code in the shader : 

```
if (round(_SelectCell) == 1.0 && id.x == _SelectedCellX && id.y == _SelectedCellY)
			
{
    brightness = _SelectedColor.w;
    color = _SelectedColor;
			
}
```
And then replace the following variable inside the block with new ones you create  : 

`_SelectedCell` is the toggle variable that is set to 1 when you want to highlight the selected cell.

`_SelectedCellX` and `_SelectedCellY` are the GUI set params used to select a cell.

`_SelectedColor` is the applied color.

If you just want another cell selected and keep the same color, make some new X and Y values but still use the `_SelectedColor `value in the new if block.

You can also change the conditions to work with a "range" of selected values by defining some new variables, using two selected positions you can draw "lines" of selected cells on the grid. Using a single selected cell and a new "range" variable and some basic math you can select circles or square area of cells.

Just remember that the more if blocks you use the slower the shader will become.
